### ISSUE TITLE
Add Pagination Support

### ISSUE THREAD

**Issue by ebaizel** [decentralized-identity/sidetree-ethereum#18]
Related to https://github.com/decentralized-identity/sidetree-core/issues/37

We want to be able to fetch batches by their corresponding transaction numbers.  Each batch added to the smart contract will have a transaction number, starting at 1 and incrementing by 1 for each added batch.

Sample response: https://github.com/decentralized-identity/sidetree-core/blob/master/docs/implementation.md#response-body-example

An open question is how many transactions in addition to this one do we want to return?  The spec keeps this open.  It would help to understand how this is intended to be used.  If it's for paginating through all transactions, then returning 10 (or more) makes sense, or having that be another request parameter.

@thehenrytsai thoughts?

**Comment by thehenrytsai** [comment]
The only intended use of the API currently is for a Sidtree node (sidetree-core) to fetch ALL the transactions starting at a certain point in time.

The intention is to let the blockchain implementation return all transactions that are known at the time of asking **immediately** so Sidetree can start processing them, there is no point IMO for the sidetree-core to specify the number of transactions to return in because: 1. Would the blockchain layer need to wait if the transaction count known falls short of that number until the asked size is met?  2. If it returns the exact number of transactions as asked, does the Sidetree node need to ask for more immediately? 3. The Sidetree node really just wants to know ALL transactions available, it might as well specify a very large number, like 1000000, is seems rather arbitrary whatever that number is. Thus I opted for just having a flag in the response indicating if there are more transactions or not, and let the blockchain layer decide, with expectation that the layer doesn't return 1 at a time if it knows of 10K.

Hopefully it makes sense. Happy to discuss further.

**Comment by thehenrytsai** [comment]
Hi @ebaizel, cache is a major component in the [sidetree-core architecture](https://github.com/decentralized-identity/sidetree-core/blob/master/docs/implementation.md#overview), we are currently calling it the _DID Cache_. You can see from the architecture diagram that lookups/resolves are intended to hit the DID Cache for perf reasons as you suggested. The description of the DID Cache can be found [further down](https://github.com/decentralized-identity/sidetree-core/blob/master/docs/implementation.md#did-cache) the same implementation doc, but more details can probably be provided. In fact, I plan to merge the first in-memory implementation of it into master sometime today, with the intention that persistence coincidentally probably using localdb to come within a week or two. It is by no means the final version, but you can take a look at the pull request [here](https://github.com/decentralized-identity/sidetree-core/pull/45) and give comments if you want.
